#
#   - JazzHands::Krb5 -
#   This spec file was automatically generated by cpan2rpm [ver: 2.028]
#   The following arguments were used:
#       --url=http://www.appnexus.com '--author=K Z Win <kwin@appnexus.com>' '--packager=K Z Win <kwin@appnexus.com>' --group=Applications/AppNexus --no-sign --no-sign --release=6 --requires=perl(JazzHands::AppAuthAL),perl-Authen-Krb5-Admin,perl-Authen-Krb5 --provides=perl(JazzHands::Krb5),perl(JazzHands::Krb5::Tool) --force /home/kwin/SOURCES/JazzHands-Krb5.tar.gz
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define rpmbase perl-jazzhands-krb5
%define pkgname JazzHands-Krb5
%define filelist %{pkgname}-%{version}-filelist
%define NVR %{pkgname}-%{version}-%{release}
%define maketest 0

Name:      perl-JazzHands-Krb5
summary:   JazzHands-Krb5 - Perl module
Version:   __VERSION__
release:   0
license:   Artistic
Group:      System/Management
Url:        http://www.jazzhands.net/
Source0:   %{rpmbase}-%{version}.tar.gz
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-buildroot
buildarch: noarch
%if 0%{?suse_version}
%else
%if 0%{?rhel} < 6
BuildRequires: perl(ExtUtils::MakeMaker)
%else
BuildRequires: perl-ExtUtils-MakeMaker
%endif
%endif
provides:  perl(JazzHands::Krb5)
provides:  perl(JazzHands::Krb5::Tool)
requires:  perl(JazzHands::AppAuthAL)
requires:  perl-Authen-Krb5-Admin
requires:  perl-Authen-Krb5

%description
JazzHands Internal Interface to using Kerberos

#
# This package was generated automatically with the cpan2rpm
# utility.  To get this software or for more information
# please visit: http://perl.arix.com/
#

%prep
%setup -q -n %{rpmbase}-%{version}

make -f Makefile.jazzhands BUILDPERL=%{__perl}

%install
make -f Makefile.jazzhands INSTALLROOT=%{buildroot} prefix=%{prefix} BUILDPERL=%{__perl} install

%clean
make -f Makefile.jazzhands clean

%files
%defattr(-,root,root)
##  %doc Changes README
%{perl_vendorlib}/*
# %{_mandir}/man3/*

