#
#   - JazzHands::Krb5 -
#   This spec file was automatically generated by cpan2rpm [ver: 2.028]
#   The following arguments were used:
#       --url=http://www.appnexus.com '--author=K Z Win <kwin@appnexus.com>' '--packager=K Z Win <kwin@appnexus.com>' --group=Applications/AppNexus --no-sign --no-sign --release=6 --requires=perl(JazzHands::AppAuthAL),perl-Authen-Krb5-Admin,perl-Authen-Krb5 --provides=perl(JazzHands::Krb5),perl(JazzHands::Krb5::Tool) --force /home/kwin/SOURCES/JazzHands-Krb5.tar.gz
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define rpmbase perl-JazzHands-Krb5
%define pkgname JazzHands-Krb5
%define filelist %{pkgname}-%{version}-filelist
%define NVR %{pkgname}-%{version}-%{release}
%define maketest 0

name:      perl-JazzHands-Krb5
summary:   JazzHands-Krb5 - Perl module
version:   0.58.9
release:   0
license:   Artistic
Group:      System/Management
Url:        http://www.jazzhands.net/
Source0:   %{rpmbase}-%{version}.tar.gz
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-buildroot
buildarch: noarch
BuildRequires: perl-ExtUtils-MakeMaker
provides:  perl(JazzHands::Krb5)
provides:  perl(JazzHands::Krb5::Tool)
requires:  perl(JazzHands::AppAuthAL)
requires:  perl-Authen-Krb5-Admin
requires:  perl-Authen-Krb5

%description
None.

#
# This package was generated automatically with the cpan2rpm
# utility.  To get this software or for more information
# please visit: http://perl.arix.com/
#

%prep
%setup -q -n %{rpmbase}-%{version}

%{__perl} Makefile.PL INSTALLDIRS=vendor PREFIX="%{buildroot}%{_prefix}"  && %{__make}


%install
[ "%{buildroot}" != "/" ] && rm -rf %{buildroot}

make pure_install

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

cmd=/usr/share/spec-helper/compress_files
[ -x $cmd ] || cmd=/usr/lib/rpm/brp-compress
[ -x $cmd ] && $cmd

# SuSE Linux
if [ -e /etc/SuSE-release -o -e /etc/UnitedLinux-release ]
then
    %{__mkdir_p} %{buildroot}/var/adm/perl-modules
    %{__cat} `find %{buildroot} -name "perllocal.pod"`  \
        | %{__sed} -e s+%{buildroot}++g                 \
        > %{buildroot}/var/adm/perl-modules/%{name}
fi

# remove special files
find %{buildroot} -name "perllocal.pod" \
    -o -name ".packlist"                \
    -o -name "*.bs"                     \
    |xargs -i rm -f {}

# no empty directories
find %{buildroot}%{_prefix}             \
    -type d -depth                      \
    -exec rmdir {} \; 2>/dev/null

%{__perl} -MFile::Find -le '
    find({ wanted => \&wanted, no_chdir => 1}, "%{buildroot}");
    print "%doc  Changes README";
    for my $x (sort @dirs, @files) {
        push @ret, $x unless indirs($x);
        }
    print join "\n", sort @ret;

    sub wanted {
        return if /auto$/;

        local $_ = $File::Find::name;
        my $f = $_; s|^\Q%{buildroot}\E||;
        return unless length;
        return $files[@files] = $_ if -f $f;

        $d = $_;
        /\Q$d\E/ && return for reverse sort @INC;
        $d =~ /\Q$_\E/ && return
            for qw|/etc %_prefix/man %_prefix/bin %_prefix/share|;

        $dirs[@dirs] = $_;
        }

    sub indirs {
        my $x = shift;
        $x =~ /^\Q$_\E\// && $x ne $_ && return 1 for @dirs;
        }
    ' > %filelist

[ -z %filelist ] && {
    echo "ERROR: empty %files listing"
    exit -1
    }

%clean
[ "%{buildroot}" != "/" ] && rm -rf %{buildroot}

%files -f %filelist
%defattr(-,root,root)

%changelog
* Tue Oct 7 2014 kovert@omniscient.com 0.58.9
  - split out to its own thing
* Thu Aug 9 2012 kwin@appnexus.com 0.01
  - Initial build.

