SOURCES= \
	JazzHands/Apache/API/Common.pm \
	JazzHands/Apache/API/Container.pm

all:
	@echo Nothing to build

install:
	mkdir -p $(INSTALLROOT)/$(PREFIX)
	for f in $(SOURCES); do \
		install -m 0755 -d $(INSTALLROOT)/$(PREFIX)/`dirname $$f` ; \
		install -m 0755 -c lib/$$f $(INSTALLROOT)/$(PREFIX)/`dirname $$f` ; \
	done

clean:
	rm -rf $(INSTALLROOT)

distclean: clean
