--
-- Copyright (c) 2016 Todd Kover
-- All rights reserved.
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--      http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

INSERT INTO val_iso_currency_code (
	iso_currency_code, description, currency_symbol
) VALUES
	('AFN','Afghanistan Afghani','؋'),
	('ALL','Albania Lek','Lek'),
	('ANG','Netherlands Antilles Guilder','ƒ'),
	('ARS','Argentina Peso','$'),
	('AUD','Australia Dollar','$'),
	('AWG','Aruba Guilder','ƒ'),
	('AZN','Azerbaijan New Manat','ман'),
	('BAM','Bosnia and Herzegovina Convertible Marka','KM'),
	('BBD','Barbados Dollar','$'),
	('BGN','Bulgaria Lev','лв'),
	('BMD','Bermuda Dollar','$'),
	('BND','Brunei Darussalam Dollar','$'),
	('BOB','Bolivia Bolíviano','$b'),
	('BRL','Brazil Real','R$'),
	('BSD','Bahamas Dollar','$'),
	('BWP','Botswana Pula','P'),
	('BYR','Belarus Ruble','p.'),
	('BZD','Belize Dollar','BZ$'),
	('CAD','Canada Dollar','$'),
	('CHF','Switzerland Franc','CHF'),
	('CLP','Chile Peso','$'),
	('CNY','China Yuan Renminbi','¥'),
	('COP','Colombia Peso','$'),
	('CRC','Costa Rica Colon','₡'),
	('CUP','Cuba Peso','₱'),
	('CZK','Czech Republic Koruna','Kč'),
	('DKK','Denmark Krone','kr'),
	('DOP','Dominican Republic Peso','RD$'),
	('EGP','Egypt Pound','£'),
	('EUR','Euro Member Countries','€'),
	('FJD','Fiji Dollar','$'),
	('FKP','Falkland Islands (Malvinas) Pound','£'),
	('GBP','United Kingdom Pound','£'),
	('GGP','Guernsey Pound','£'),
	('GHS','Ghana Cedi','¢'),
	('GIP','Gibraltar Pound','£'),
	('GTQ','Guatemala Quetzal','Q'),
	('GYD','Guyana Dollar','$'),
	('HKD','Hong Kong Dollar','$'),
	('HNL','Honduras Lempira','L'),
	('HRK','Croatia Kuna','kn'),
	('HUF','Hungary Forint','Ft'),
	('IDR','Indonesia Rupiah','Rp'),
	('ILS','Israel Shekel','₪'),
	('IMP','Isle of Man Pound','£'),
	('INR','India Rupee','₹'),
	('IRR','Iran Rial','﷼'),
	('ISK','Iceland Krona','kr'),
	('JEP','Jersey Pound','£'),
	('JMD','Jamaica Dollar','J$'),
	('JPY','Japan Yen','¥'),
	('KGS','Kyrgyzstan Som','лв'),
	('KHR','Cambodia Riel','៛'),
	('KPW','Korea (North) Won','₩'),
	('KRW','Korea (South) Won','₩'),
	('KYD','Cayman Islands Dollar','$'),
	('KZT','Kazakhstan Tenge','лв'),
	('LAK','Laos Kip','₭'),
	('LBP','Lebanon Pound','£'),
	('LKR','Sri Lanka Rupee','₨'),
	('LRD','Liberia Dollar','$'),
	('MKD','Macedonia Denar','ден'),
	('MNT','Mongolia Tughrik','₮'),
	('MUR','Mauritius Rupee','₨'),
	('MXN','Mexico Peso','$'),
	('MYR','Malaysia Ringgit','RM'),
	('MZN','Mozambique Metical','MT'),
	('NAD','Namibia Dollar','$'),
	('NGN','Nigeria Naira','₦'),
	('NIO','Nicaragua Cordoba','C$'),
	('NOK','Norway Krone','kr'),
	('NPR','Nepal Rupee','₨'),
	('NZD','New Zealand Dollar','$'),
	('OMR','Oman Rial','﷼'),
	('PAB','Panama Balboa','B/.'),
	('PEN','Peru Sol','S/.'),
	('PHP','Philippines Peso','₱'),
	('PKR','Pakistan Rupee','₨'),
	('PLN','Poland Zloty','zł'),
	('PYG','Paraguay Guarani','Gs'),
	('QAR','Qatar Riyal','﷼'),
	('RON','Romania New Leu','lei'),
	('RSD','Serbia Dinar','Дин.'),
	('RUB','Russia Ruble','руб'),
	('SAR','Saudi Arabia Riyal','﷼'),
	('SBD','Solomon Islands Dollar','$'),
	('SCR','Seychelles Rupee','₨'),
	('SEK','Sweden Krona','kr'),
	('SGD','Singapore Dollar','$'),
	('SHP','Saint Helena Pound','£'),
	('SOS','Somalia Shilling','S'),
	('SRD','Suriname Dollar','$'),
	('SVC','El Salvador Colon','$'),
	('SYP','Syria Pound','£'),
	('THB','Thailand Baht','฿'),
	('TRY','Turkey Lira','₺'),
	('TTD','Trinidad and Tobago Dollar','TT$'),
	('TVD','Tuvalu Dollar','$'),
	('TWD','Taiwan New Dollar','NT$'),
	('UAH','Ukraine Hryvnia','₴'),
	('USD','United States Dollar','$'),
	('UYU','Uruguay Peso','$U'),
	('UZS','Uzbekistan Som','лв'),
	('VEF','Venezuela Bolivar','Bs'),
	('VND','Viet Nam Dong','₫'),
	('XCD','East Caribbean Dollar','$'),
	('YER','Yemen Rial','﷼'),
	('ZAR','South Africa Rand','R'),
	('ZWD','Zimbabwe Dollar','Z$');

