#
#   - JazzHands::LDAP -
#   This spec file was automatically generated by cpan2rpm [ver: 2.028]
#   The following arguments were used:
#       --url=http://www.appnexus.com '--author=K Z Win <kwin@appnexus.com>' '--packager=K Z Win <kwin@appnexus.com>' --group=Applications/AppNexus --no-sign --no-sign --release=9 --requires=perl-JazzHands-AppAuthAL,perl-LDAP --provides=perl(JazzHands::LDAP) --force /home/kwin/rpm/SOURCES/JazzHands-LDAP.tar.gz
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define pkgname perl-jazzhands-ldap
%define filelist %{pkgname}-%{version}-filelist
%define NVR %{pkgname}-%{version}-%{release}
%define maketest 1

Name:      perl-JazzHands-LDAP
summary:   JazzHands-LDAP - Perl module
version:   __VERSION__
release:   0
license:   Apache
url:       http://www.jazzhands.net
Source0:   %{pkgname}-%{version}.tar.gz
%if 0%{?suse_version}
%else
%if 0%{?rhel} < 6
BuildRequires: perl(ExtUtils::MakeMaker)
BuildRequires: perl(JazzHands::AppAuthAL)
BuildRequires: perl(Net::LDAP)
%else
BuildRequires: perl-ExtUtils-MakeMaker
BuildRequires: perl-JazzHands-AppAuthAL, perl-LDAP
%endif
%endif
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-buildroot
buildarch: noarch
prefix:    %(echo %{_prefix})
provides:  perl(JazzHands::LDAP)
requires:  perl-JazzHands-AppAuthAL
requires:  perl-LDAP

%description
None.

#
# This package was generated automatically with the cpan2rpm
# utility.  To get this software or for more information
# please visit: http://perl.arix.com/
#

%prep
%setup -q -n %{pkgname}-%{version}
make -f Makefile.jazzhands BUILDPERL=%{__perl}

%install
make -f Makefile.jazzhands INSTALLROOT=%{buildroot} prefix=%{prefix} BUILDPERL=%{__perl} install

%clean
make -f Makefile.jazzhands clean

%files
%defattr(-,root,root)
##  %doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

