
all:
	$(BUILDPERL) Makefile.PL INSTALLDIRS=vendor  && $(MAKE)

install:
	@ if [ -z "$(DESTDIR)" ] ; then echo 1>&2 Must set DESTDIR;exit 1;fi
	echo Doing install
	rm -rf $(DESTDIR)
	mkdir -p $(DESTDIR)/${prefix}
	make pure_install

	find $(DESTDIR) -type f -name .packlist -exec rm -f {} \;
	find $(DESTDIR) -depth -type d -exec rmdir {} 2>/dev/null \;
	find $(DESTDIR) -name Makefile -print |xargs rm -f
	echo Done install

clean:
	[ -f Makefile ] && make distclean


distclean: clean
