--
--  This is the senior/admin role 
-- $Id$
--

CREATE ROLE "ADMIN_ROLE" NOT IDENTIFIED;
 
GRANT "CONNECT" TO "ADMIN_ROLE";
 
GRANT "RESOURCE" TO "ADMIN_ROLE";

GRANT "RO_ROLE" TO "ADMIN_ROLE";

GRANT "IUD_ROLE" TO "ADMIN_ROLE";

GRANT "EXEC_PKG_ROLE" TO "ADMIN_ROLE";

GRANT SELECT ANY DICTIONARY TO "ADMIN_ROLE";
 

