-- Copyright (c) 2005-2010, Vonage Holdings Corp.
-- All rights reserved.
--
-- Redistribution and use in source and binary forms, with or without
-- modification, are permitted provided that the following conditions are met:
--     * Redistributions of source code must retain the above copyright
--       notice, this list of conditions and the following disclaimer.
--     * Redistributions in binary form must reproduce the above copyright
--       notice, this list of conditions and the following disclaimer in the
--       documentation and/or other materials provided with the distribution.
--
-- THIS SOFTWARE IS PROVIDED BY VONAGE HOLDINGS CORP. ''AS IS'' AND ANY
-- EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
-- WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
-- DISCLAIMED. IN NO EVENT SHALL VONAGE HOLDINGS CORP. BE LIABLE FOR ANY
-- DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
-- (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
-- LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
-- ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-- (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
-- SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--
--
-- $Id$
--


update aud$system_password
set 
 CRYPT=NVL2(CRYPT,substr(ROWID,1,13),NULL),
 MD5HASH=NVL2(MD5HASH,substr(ROWID,1,50),NULL),
 SHA1=NVL2(SHA1,substr(ROWID,1,50),NULL),
 BLOWFISH=NVL2(BLOWFISH,substr(ROWID,1,50),NULL),
 LANMAN=NVL2(LANMAN,substr(ROWID,1,50),NULL),
 NT=NVL2(NT,substr(ROWID,1,50),NULL),
 SASL_CRAM_MD5=NVL2(SASL_CRAM_MD5,substr(ROWID,1,50),NULL),
 SASL_DIGEST_MD5=NVL2(SASL_DIGEST_MD5,SUBSTR(ROWID,35),NULL),
 JABBER=NVL2(JABBER,substr(ROWID,1,50),NULL),
 NETWORK_DEVICE=NVL2(NETWORK_DEVICE,substr(ROWID,1,50),NULL),
 ORACLE_PASSWORD=NVL2(ORACLE_PASSWORD,substr(ROWID,1,50),NULL),
 MYSQL_PASSWORD=NVL2(MYSQL_PASSWORD,substr(ROWID,1,50),NULL),
 MYSQL40_PASSWORD=NVL2(MYSQL40_PASSWORD,substr(ROWID,1,50),NULL),
 CCA_PASSWORD=NVL2(CCA_PASSWORD,substr(ROWID,1,50),NULL),
 POSTGRES_PASSWORD=NVL2(POSTGRES_PASSWORD,substr(ROWID,1,50),NULL),
 ENTERPRISEDB_PASSWORD=NVL2(ENTERPRISEDB_PASSWORD,substr(ROWID,1,50),NULL),
 ORA_APPS_PASSWORD=NVL2(ORA_APPS_PASSWORD,substr(ROWID,1,50),NULL)
;


alter trigger jazzhands.AUDTRG$SYSTEM_PASSWORD disable;



update system_password
set 
 CRYPT=NVL2(CRYPT,substr(ROWID,1,13),NULL),
 MD5HASH=NVL2(MD5HASH,substr(ROWID,1,50),NULL),
 SHA1=NVL2(SHA1,substr(ROWID,1,50),NULL),
 BLOWFISH=NVL2(BLOWFISH,substr(ROWID,1,50),NULL),
 LANMAN=NVL2(LANMAN,substr(ROWID,1,50),NULL),
 NT=NVL2(NT,substr(ROWID,1,50),NULL),
 SASL_CRAM_MD5=NVL2(SASL_CRAM_MD5,substr(ROWID,1,50),NULL),
 SASL_DIGEST_MD5=NVL2(SASL_DIGEST_MD5,SUBSTR(ROWID,35),NULL),
 JABBER=NVL2(JABBER,substr(ROWID,1,50),NULL),
 NETWORK_DEVICE=NVL2(NETWORK_DEVICE,substr(ROWID,1,50),NULL),
 ORACLE_PASSWORD=NVL2(ORACLE_PASSWORD,substr(ROWID,1,50),NULL),
 MYSQL_PASSWORD=NVL2(MYSQL_PASSWORD,substr(ROWID,1,50),NULL),
 MYSQL40_PASSWORD=NVL2(MYSQL40_PASSWORD,substr(ROWID,1,50),NULL),
 CCA_PASSWORD=NVL2(CCA_PASSWORD,substr(ROWID,1,50),NULL),
 POSTGRES_PASSWORD=NVL2(POSTGRES_PASSWORD,substr(ROWID,1,50),NULL),
 ENTERPRISEDB_PASSWORD=NVL2(ENTERPRISEDB_PASSWORD,substr(ROWID,1,50),NULL),
 ORA_APPS_PASSWORD=NVL2(ORA_APPS_PASSWORD,substr(ROWID,1,50),NULL)
;

alter trigger jazzhands.AUDTRG$SYSTEM_PASSWORD enable;




update aud$application_instance
set password=NVL2(PASSWORD,substr(ROWID,1,80),NULL);



alter trigger jazzhands.AUDTRG$APPLICATION_INSTANCE disable;

update application_instance
set password=NVL2(PASSWORD,substr(ROWID,1,80),NULL);

alter trigger jazzhands.AUDTRG$APPLICATION_INSTANCE enable;



