-- Copyright (c) 2005-2010, Vonage Holdings Corp.
-- All rights reserved.
--
-- Redistribution and use in source and binary forms, with or without
-- modification, are permitted provided that the following conditions are met:
--     * Redistributions of source code must retain the above copyright
--       notice, this list of conditions and the following disclaimer.
--     * Redistributions in binary form must reproduce the above copyright
--       notice, this list of conditions and the following disclaimer in the
--       documentation and/or other materials provided with the distribution.
--
-- THIS SOFTWARE IS PROVIDED BY VONAGE HOLDINGS CORP. ''AS IS'' AND ANY
-- EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
-- WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
-- DISCLAIMED. IN NO EVENT SHALL VONAGE HOLDINGS CORP. BE LIABLE FOR ANY
-- DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
-- (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
-- LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
-- ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-- (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
-- SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--
--  Read only role
-- $Id$
--



create role ro_role;

grant create session to ro_role;


-------

GRANT SELECT ON JAZZHANDS.APPLICATION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.APPLICATION_INSTANCE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$APPLICATION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$APPLICATION_INSTANCE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$BADGE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$BADGE_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$CIRCUIT TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$COMPANY TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$COMPOSITE_OS_VERSION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$DEPT TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$DEPT_MEMBER TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$DEVICE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$DEVICE_COLLECTION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$DEVICE_COLLECTION_HIER TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$device_collection_device TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$DEVICE_COLLECTION_UCLASS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$DEVICE_FUNCTION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$DEVICE_NOTE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$DEVICE_POWER_CONNECTION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$DEVICE_POWER_INTERFACE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$DEVICE_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$DEVICE_TYPE_POWER_PORT_TEM TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$DEVICE_TYPE_SERIAL_PORT_TE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$DHCP_RANGE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$DNS_DOMAIN TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$DNS_RECORD TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$ENCAPSULATION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$KERBEROS_REALM TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$KLOGIN TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$KLOGIN_MCLASS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$LAYER1_CONNECTION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$LAYER2_ENCAPSULATION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$LOCATION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$MCLASS_APPLICATION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$MCLASS_EXTRA_FILE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$MCLASS_GROUP TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$MCLASS_PROPERTY_OVERRIDE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$MCLASS_UNIX_PROP TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$MCLASS_WWW_GROUP TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$NETBLOCK TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$NETWORK_INTERFACE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$NETWORK_SERVICE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$OPERATING_SYSTEM TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$PARTNER TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$PHYSICAL_CONNECTION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$PHYSICAL_PORT TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$PSEUDO_KLOGIN TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$SECONDARY_NETBLOCK TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$SITE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$SITE_NETBLOCK TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$SNMP_COMMSTR TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$STATIC_ROUTE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$STATIC_ROUTE_TEMPLATE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$SYSTEM_PARKING_PASS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$SYSTEM_PASSWORD TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$SYSTEM_USER TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$SYSTEM_USER_IMAGE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$SYSTEM_USER_LOCATION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$SYSTEM_USER_PHONE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$SYSTEM_USER_TOKEN TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$SYSTEM_USER_VEHICLE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$SYSTEM_USER_XREF TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$TOKEN TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$UCLASS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$UCLASS_DEPT TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$UCLASS_HIER TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$UCLASS_PROPERTY_OVERRIDE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$UCLASS_USER TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$UNIX_GROUP TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$UNIX_GROUP_MEMBER TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$UNIX_GROUP_PROPERTY TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$UNIX_GROUP_UCLASS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$USER_UNIX_INFO TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_AUTHENTICATION_METHOD TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_BADGE_STATUS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_CABLE_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_COUNTRY_CODE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_DATABASE_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_DEVICE_COLLECTION_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_DEVICE_FUNCTION_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_DNS_CLASS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_DNS_SRV_SERVICE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_DNS_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_ENCAPSULATION_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_IMAGE_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_MCLASS_EXTRA_FILE_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_MCLASS_UNIX_HOME_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_MCLASS_UNIX_PW_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_NETBLOCK_STATUS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_NETWORK_INTERFACE_PURP TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_NETWORK_INTERFACE_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_NETWORK_SERVICE_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_OFFICE_SITE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_OWNERSHIP_STATUS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_PHONE_NUMBER_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_PLUG_STYLE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_PORT_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_PRODUCTION_STATE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_REPORTING_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_SNMP_COMMSTR_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_STATUS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_SYSTEM_USER_STATUS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_SYSTEM_USER_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_TOKEN_STATUS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_TOKEN_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_UCLASS_PROPERTY_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_UCLASS_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_UNIX_GROUP_PROP_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_USER_LOCATION_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VLAN_RANGE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$WWW_GROUP TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$WWW_GROUP_MEMBER TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.BADGE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.BADGE_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.CIRCUIT TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.COMPANY TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.COMPOSITE_OS_VERSION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.CREATE$JAVA$LOB$TABLE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.DEPT TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.DEPT_MEMBER TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.DEVICE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.DEVICE_COLLECTION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.DEVICE_COLLECTION_HIER TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.device_collection_device TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.DEVICE_COLLECTION_UCLASS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.DEVICE_FUNCTION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.DEVICE_NOTE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.DEVICE_POWER_CONNECTION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.DEVICE_POWER_INTERFACE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.DEVICE_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.DEVICE_TYPE_POWER_PORT_TEMPLT TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.DEVICE_TYPE_SERIAL_PORT_TEMPLT TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.DHCP_RANGE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.DNS_DOMAIN TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.DNS_RECORD TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.ENCAPSULATION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.KERBEROS_REALM TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.KLOGIN TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.KLOGIN_MCLASS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.LAYER1_CONNECTION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.LAYER2_ENCAPSULATION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.LOCATION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.MCLASS_APPLICATION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.MCLASS_EXTRA_FILE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.MCLASS_GROUP TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.MCLASS_PROPERTY_OVERRIDE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.MCLASS_UNIX_PROP TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.MCLASS_WWW_GROUP TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.NETBLOCK TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.NETWORK_INTERFACE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.NETWORK_SERVICE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.OPERATING_SYSTEM TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.PARTNER TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.PHYSICAL_CONNECTION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.PHYSICAL_PORT TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.PSEUDO_KLOGIN TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.SECONDARY_NETBLOCK TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.SITE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.SITE_NETBLOCK TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.SNMP_COMMSTR TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.STATIC_ROUTE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.STATIC_ROUTE_TEMPLATE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.SYSTEM_PARKING_PASS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.SYSTEM_PASSWORD TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.SYSTEM_USER TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.SYSTEM_USER_IMAGE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.SYSTEM_USER_LOCATION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.SYSTEM_USER_PHONE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.SYSTEM_USER_TOKEN TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.SYSTEM_USER_VEHICLE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.SYSTEM_USER_XREF TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.TOKEN TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.UCLASS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.UCLASS_DEPT TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.UCLASS_HIER TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.UCLASS_PROPERTY_OVERRIDE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.UCLASS_USER TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.UNIX_GROUP TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.UNIX_GROUP_MEMBER TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.UNIX_GROUP_PROPERTY TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.UNIX_GROUP_UCLASS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.USER_UNIX_INFO TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_AUTHENTICATION_METHOD TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_BADGE_STATUS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_CABLE_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_COUNTRY_CODE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_DATABASE_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_DEVICE_COLLECTION_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_DEVICE_FUNCTION_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_DNS_CLASS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_DNS_SRV_SERVICE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_DNS_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_ENCAPSULATION_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_IMAGE_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_MCLASS_EXTRA_FILE_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_MCLASS_UNIX_HOME_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_MCLASS_UNIX_PW_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_NETBLOCK_STATUS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_NETWORK_INTERFACE_PURPOSE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_NETWORK_INTERFACE_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_NETWORK_SERVICE_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_OFFICE_SITE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_OWNERSHIP_STATUS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_PHONE_NUMBER_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_PLUG_STYLE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_PORT_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_PRODUCTION_STATE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_REPORTING_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_SNMP_COMMSTR_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_STATUS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_SYSTEM_USER_STATUS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_SYSTEM_USER_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_TOKEN_STATUS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_TOKEN_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_UCLASS_PROPERTY_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_UCLASS_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_UNIX_GROUP_PROP_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_USER_LOCATION_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VLAN_RANGE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.WWW_GROUP TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.WWW_GROUP_MEMBER TO RO_ROLE;

GRANT SELECT ON JAZZHANDS.SYSTEM_USER_NOTE TO RO_ROLE;

GRANT SELECT ON JAZZHANDS.SW_PACKAGE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.SW_PACKAGE_RELATION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.SW_PACKAGE_RELEASE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.SW_PACKAGE_REPOSITORY TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.TOKEN TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.TOKEN_SEQUENCE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_BAUD TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_DATA_BITS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_DEVICE_AUTO_MGMT_PROTOCOL TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_FLOW_CONTROL TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_PACKAGE_RELATION_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_PARITY TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_PROCESSOR_ARCHITECTURE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_STOP_BITS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_SW_PACKAGE_FORMAT TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_SYMBOLIC_TRACK_NAME TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_UCLASS_PROPERTY_NAME TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_UPGRADE_SEVERITY TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_VOE_STATE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VOE_RELATION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VOE_SW_PACKAGE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VOE_SYMBOLIC_TRACK TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VOE TO RO_ROLE;

GRANT SELECT ON JAZZHANDS.AUD$SW_PACKAGE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$SW_PACKAGE_RELATION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$SW_PACKAGE_RELEASE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$SW_PACKAGE_REPOSITORY TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$SYSTEM_USER_NOTE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$TOKEN TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_BAUD TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_DATA_BITS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_DEVICE_AUTO_MGMT_PROTO TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_FLOW_CONTROL TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_PACKAGE_RELATION_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_PARITY TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_PROCESSOR_ARCHITECTURE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_STOP_BITS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_SW_PACKAGE_FORMAT TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_SYMBOLIC_TRACK_NAME TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_UCLASS_PROPERTY_NAME TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_UPGRADE_SEVERITY TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_VOE_STATE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VOE_RELATION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VOE_SW_PACKAGE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VOE_SYMBOLIC_TRACK TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VOE TO RO_ROLE;

-------




---
GRANT SELECT ON JAZZHANDS.DNS_RECORD_RELATION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.SUDO_ALIAS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.SUDO_DEFAULT TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.SUDO_UCLASS_DEVICE_COLLECTION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_DNS_RECORD_RELATION_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_PORT_PURPOSE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.VAL_SW_PACKAGE_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$DNS_RECORD_RELATION TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$SUDO_ALIAS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$SUDO_DEFAULT TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$SUDO_UCLASS_DEVICE_COLLECT TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_DNS_RECORD_RELATION_TY TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_PORT_PURPOSE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.AUD$VAL_SW_PACKAGE_TYPE TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.V_LOGIN_CHANGES TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.V_LOGIN_CHANGES_EXTRACT TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.V_TOKEN TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.V_USER_DELETIONS TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.V_USER_DELETIONS_EXTRACT TO RO_ROLE;
GRANT SELECT ON JAZZHANDS.V_USER_EXTRACT TO RO_ROLE;




