
-- Copyright (c) 2005-2010, Vonage Holdings Corp.
-- All rights reserved.
--
-- Redistribution and use in source and binary forms, with or without
-- modification, are permitted provided that the following conditions are met:
-- * Redistributions of source code must retain the above copyright
-- notice, this list of conditions and the following disclaimer.
-- * Redistributions in binary form must reproduce the above copyright
-- notice, this list of conditions and the following disclaimer in the
-- documentation and/or other materials provided with the distribution.
--
-- THIS SOFTWARE IS PROVIDED BY VONAGE HOLDINGS CORP. ''AS IS'' AND ANY
-- EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
-- WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
-- DISCLAIMED. IN NO EVENT SHALL VONAGE HOLDINGS CORP. BE LIABLE FOR ANY
-- DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
-- (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
-- LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
-- ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-- (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
-- SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--
--
--
-- $Id$
--



DROP TRIGGER C_TIUBR_UNIX_GROUP;



DROP TRIGGER TIB_UNIX_GROUP;



DROP TRIGGER TUB_UNIX_GROUP;



DROP TRIGGER C_TIUBR_UCLASS_USER;



DROP TRIGGER TUB_UCLASS_USER;



DROP TRIGGER C_TIBUR_VAL_PROPERTY_VALUE;



DROP TRIGGER TUB_VAL_PROPERTY_VALUE;



DROP TRIGGER C_TIUBR_VAL_DNS_DOMAIN_TYPE;



DROP TRIGGER TUB_VAL_DNS_DOMAIN_TYPE;



DROP TRIGGER C_TIBUR_DEVICE_TICKET;



DROP TRIGGER TUB_DEVICE_TICKET;



DROP TRIGGER C_TIBUR_VAL_PROPERTY_TYPE;



DROP TRIGGER TUB_VAL_PROPERTY_TYPE;



DROP TRIGGER C_TIBUR_VAL_PROPERTY_DATA_TYPE;



DROP TRIGGER TUB_VAL_PROPERTY_DATA_TYPE;



DROP TRIGGER C_TIBUR_VAL_PROPERTY;



DROP TRIGGER TUB_VAL_PROPERTY;



DROP TRIGGER C_TIBUR_PROPERTY;



DROP TRIGGER K_TAIU_NONROW_PROPERTY;



DROP TRIGGER K_TBIU_NONROW_PROPERTY;



DROP TRIGGER K_TBIU_PROPERTY;



DROP TRIGGER TIB_PROPERTY;



DROP TRIGGER TUB_PROPERTY;



DROP TRIGGER C_TIUBR_VAL_ENCRYPT_KEY_PURP;



DROP TRIGGER TUB_VAL_ENCRYPT_KEY_PURPOSE;



DROP TRIGGER C_TIUBR_NETWORK_INTERFACE;



DROP TRIGGER TIB_NETWORK_INTERFACE;



DROP TRIGGER TUB_NETWORK_INTERFACE;



DROP TRIGGER C_TIUBR_VAL_APP_KEY_VALUES;



DROP TRIGGER TUB_VAL_APP_KEY_VALUES;



DROP TRIGGER C_TIUBR_VAL_UPGRADE_SEVERITY;



DROP TRIGGER TUB_VAL_UPGRADE_SEVERITY;



DROP TRIGGER C_TIUBR_PHYSICAL_PORT;



DROP TRIGGER TIB_PHYSICAL_PORT;



DROP TRIGGER TUB_PHYSICAL_PORT;



DROP TRIGGER C_TIUBR_VAL_SNMP_COMMSTR_TYPE;



DROP TRIGGER TUB_VAL_SNMP_COMMSTR_TYPE;



DROP TRIGGER C_TIUBR_SW_PACKAGE;



DROP TRIGGER TIB_SW_PACKAGE;



DROP TRIGGER TUB_SW_PACKAGE;



DROP TRIGGER C_TIUBR_VAL_SYSTEM_USER_STATUS;



DROP TRIGGER TUB_VAL_SYSTEM_USER_STATUS;



DROP TRIGGER C_TIUBR_DHCP_RANGE;



DROP TRIGGER TIB_DHCP_RANGE;



DROP TRIGGER TUB_DHCP_RANGE;



DROP TRIGGER C_TIUBR_SUDO_DEFAULT;



DROP TRIGGER TIB_SUDO_DEFAULT;



DROP TRIGGER TUB_SUDO_DEFAULT;



DROP TRIGGER C_TIUBR_UCLASS_DEPT;



DROP TRIGGER TUB_UCLASS_DEPT;



DROP TRIGGER C_TIUBR_DNS_DOMAIN;



DROP TRIGGER K_TIUBR_DNS_DOMAIN;



DROP TRIGGER TIB_DNS_DOMAIN;



DROP TRIGGER TUB_DNS_DOMAIN;



DROP TRIGGER C_TIUBR_STATIC_ROUTE_TEMPLATE;



DROP TRIGGER TIB_STATIC_ROUTE_TEMPLATE;



DROP TRIGGER TUB_STATIC_ROUTE_TEMPLATE;



DROP TRIGGER C_TIUBR_VAL_SW_PACKAGE_TYPE;



DROP TRIGGER TUB_VAL_SW_PACKAGE_TYPE;



DROP TRIGGER C_TIUBR_VAL_SYSTEM_USER_TYPE;



DROP TRIGGER TUB_VAL_SYSTEM_USER_TYPE;



DROP TRIGGER C_TIUBR_LOCATION;



DROP TRIGGER TIB_LOCATION;



DROP TRIGGER TUB_LOCATION;



DROP TRIGGER C_TIUBR_VAL_DNS_CLASS;



DROP TRIGGER TUB_VAL_DNS_CLASS;



DROP TRIGGER C_TIUBR_VAL_STOP_BITS;



DROP TRIGGER TUB_VAL_STOP_BITS;



DROP TRIGGER C_TIUBR_PARTNER;



DROP TRIGGER TIB_PARTNER;



DROP TRIGGER TUB_PARTNER;



DROP TRIGGER C_TIUBR_USER_UNIX_INFO;



DROP TRIGGER K_TIUBR_USER_UNIX_INFO;



DROP TRIGGER TIB_USER_UNIX_INFO;



DROP TRIGGER TUB_USER_UNIX_INFO;



DROP TRIGGER C_TIUBR_DEVICE_COLLECTION_MEMB;



DROP TRIGGER TUB_DEVICE_COLLECTION_MEMBER;



DROP TRIGGER C_TIUBR_VAL_PACKAGE_RELATION_T;



DROP TRIGGER TUB_VAL_PACKAGE_RELATION_TYPE;



DROP TRIGGER C_TIUBR_VAL_DNS_RECORD_RELATIO;



DROP TRIGGER TUB_VAL_DNS_RECORD_RELATION_TY;



DROP TRIGGER C_TIUBR_UCLASS_HIER;



DROP TRIGGER TUB_UCLASS_HIER;



DROP TRIGGER C_TIUBR_VAL_NETBLOCK_STATUS;



DROP TRIGGER TUB_VAL_NETBLOCK_STATUS;



DROP TRIGGER C_TIUBR_VAL_PARITY;



DROP TRIGGER TUB_VAL_PARITY;



DROP TRIGGER C_TIUBR_PSEUDO_KLOGIN;



DROP TRIGGER TIB_PSEUDO_KLOGIN;



DROP TRIGGER TUB_PSEUDO_KLOGIN;



DROP TRIGGER C_TIUBR_VAL_PORT_TYPE;



DROP TRIGGER TUB_VAL_PORT_TYPE;



DROP TRIGGER C_TIUBR_DEPT_MEMBER;



DROP TRIGGER K_TAIU_NONROW_DEPT_MEMBER;



DROP TRIGGER K_TBIU_DEPT_MEMBER;



DROP TRIGGER K_TBIU_NONROW_DEPT_MEMBER;



DROP TRIGGER TUB_DEPT_MEMBER;



DROP TRIGGER C_TIUBR_VAL_STATUS;



DROP TRIGGER TUB_VAL_STATUS;



DROP TRIGGER C_TIUBR_SUDO_UCLASS_DEVICE_COL;



DROP TRIGGER TUB_SUDO_UCLASS_DEVICE_COLLECT;



DROP TRIGGER C_TIUBR_VAL_TOKEN_STATUS;



DROP TRIGGER TUB_VAL_TOKEN_STATUS;



DROP TRIGGER C_TIUBR_VOE_SYMBOLIC_TRACK;



DROP TRIGGER TIB_VOE_SYMBOLIC_TRACK;



DROP TRIGGER TUB_VOE_SYMBOLIC_TRACK;



DROP TRIGGER C_TIUBR_SYSTEM_USER_LOCATION;



DROP TRIGGER K_TAIUD_SYS_USER_SITE;



DROP TRIGGER TIB_SYSTEM_USER_LOCATION;



DROP TRIGGER TUB_SYSTEM_USER_LOCATION;



DROP TRIGGER C_TIUBR_SYSTEM_USER_XREF;



DROP TRIGGER TUB_SYSTEM_USER_XREF;



DROP TRIGGER C_TIUBR_SUDO_ALIAS;



DROP TRIGGER TUB_SUDO_ALIAS;



DROP TRIGGER C_TIUBR_VOE_SW_PACKAGE;



DROP TRIGGER TUB_VOE_SW_PACKAGE;



DROP TRIGGER C_TIUBR_DEVICE_FUNCTION;



DROP TRIGGER TUB_DEVICE_FUNCTION;



DROP TRIGGER C_TIUBR_VAL_SW_PACKAGE_FORMAT;



DROP TRIGGER TUB_VAL_SW_PACKAGE_FORMAT;



DROP TRIGGER C_TIUBR_VAL_REPORTING_TYPE;



DROP TRIGGER TUB_VAL_REPORTING_TYPE;



DROP TRIGGER C_TIUBR_VAL_USER_LOCATION_TYPE;



DROP TRIGGER TUB_VAL_USER_LOCATION_TYPE;



DROP TRIGGER C_TIUBR_SITE_NETBLOCK;



DROP TRIGGER TUB_SITE_NETBLOCK;



DROP TRIGGER C_TIUBR_REASON_FOR_ASSIGN;



DROP TRIGGER TUB_REASON_FOR_ASSIGN;



DROP TRIGGER C_TIUBR_VAL_OFFICE_SITE;



DROP TRIGGER TUB_VAL_OFFICE_SITE;



DROP TRIGGER C_TIUBR_VAL_PHONE_NUMBER_TYPE;



DROP TRIGGER TUB_VAL_PHONE_NUMBER_TYPE;



DROP TRIGGER C_TIUBR_VAL_PORT_PURPOSE;



DROP TRIGGER TUB_VAL_PORT_PURPOSE;



DROP TRIGGER C_TIUBR_NETWORK_SERVICE;



DROP TRIGGER TIB_NETWORK_SERVICE;



DROP TRIGGER TUB_NETWORK_SERVICE;



DROP TRIGGER C_TIUBR_TOKEN;



DROP TRIGGER TIB_TOKEN;



DROP TRIGGER TUB_TOKEN;



DROP TRIGGER C_TIUBR_KLOGIN_MCLASS;



DROP TRIGGER TUB_KLOGIN_MCLASS;



DROP TRIGGER C_TIUBR_BADGE_TYPE;



DROP TRIGGER TIB_BADGE_TYPE;



DROP TRIGGER TUB_BADGE_TYPE;



DROP TRIGGER C_TIUBR_VAL_TOKEN_TYPE;



DROP TRIGGER TUB_VAL_TOKEN_TYPE;



DROP TRIGGER C_TIUBR_VAL_PLUG_STYLE;



DROP TRIGGER TUB_VAL_PLUG_STYLE;



DROP TRIGGER C_TIUBR_VLAN_RANGE;



DROP TRIGGER TIB_VLAN_RANGE;



DROP TRIGGER TUB_VLAN_RANGE;



DROP TRIGGER C_TIUBR_VAL_SYMBOLIC_TRACK_NAM;



DROP TRIGGER TUB_VAL_SYMBOLIC_TRACK_NAME;



DROP TRIGGER C_TIUBR_VAL_DEVICE_AUTO_MGMT_P;



DROP TRIGGER TUB_VAL_DEVICE_AUTO_MGMT_PROTO;



DROP TRIGGER C_TIUBR_VAL_FLOW_CONTROL;



DROP TRIGGER TUB_VAL_FLOW_CONTROL;



DROP TRIGGER C_TIUBR_APPAAL_INSTANCE_DEVICE;



DROP TRIGGER TUB_APPAAL_INSTANCE_DEVICE_COL;



DROP TRIGGER C_TIUBR_CIRCUIT;



DROP TRIGGER TIB_CIRCUIT;



DROP TRIGGER TUB_CIRCUIT;



DROP TRIGGER C_TIUBR_SNMP_COMMSTR;



DROP TRIGGER K_TBIU_SNMP_COMMSTR;



DROP TRIGGER TIB_SNMP_COMMSTR;



DROP TRIGGER TUB_SNMP_COMMSTR;



DROP TRIGGER C_TIUBR_LAYER2_ENCAPSULATION;



DROP TRIGGER TIB_LAYER2_ENCAPSULATION;



DROP TRIGGER TUB_LAYER2_ENCAPSULATION;



DROP TRIGGER C_TIUBR_DEVICE_TYPE_POWER_PORT;



DROP TRIGGER TUB_DEVICE_TYPE_POWER_PORT_TEM;



DROP TRIGGER C_TIUBR_DEVICE;



DROP TRIGGER K_TIUBR_DEVICE;



DROP TRIGGER TIB_DEVICE;



DROP TRIGGER TUB_DEVICE;



DROP TRIGGER C_TIUA_LAYER1_CONNECTION;



DROP TRIGGER C_TIUBR_LAYER1_CONNECTION;



DROP TRIGGER TIB_LAYER1_CONNECTION;



DROP TRIGGER TUB_LAYER1_CONNECTION;



DROP TRIGGER C_TIUBR_VAL_OWNERSHIP_STATUS;



DROP TRIGGER TUB_VAL_OWNERSHIP_STATUS;



DROP TRIGGER C_TIUBR_VAL_DATA_BITS;



DROP TRIGGER TUB_VAL_DATA_BITS;



DROP TRIGGER C_TIBUR_KEY_USAGE_CTGRZTION;



DROP TRIGGER TUB_KEY_USAGE_CATEGRZTN;



DROP TRIGGER C_TIUBR_SYSTEM_USER_VEHICLE;



DROP TRIGGER TIB_SYSTEM_USER_VEHICLE;



DROP TRIGGER TUB_SYSTEM_USER_VEHICLE;



DROP TRIGGER C_TIUBR_BADGE;



DROP TRIGGER TUB_BADGE;



DROP TRIGGER C_TIUA_PHYSICAL_CONNECTION;



DROP TRIGGER C_TIUBR_PHYSICAL_CONNECTION;



DROP TRIGGER TIB_PHYSICAL_CONNECTION;



DROP TRIGGER TUB_PHYSICAL_CONNECTION;



DROP TRIGGER C_TIUBR_RACK;



DROP TRIGGER TIB_RACK;



DROP TRIGGER TUB_RACK;



DROP TRIGGER C_TIUBR_APPAAL_INSTANCE;



DROP TRIGGER K_TIUBR_APPAAL_INSTANCE;



DROP TRIGGER TIB_APPAAL_INSTANCE;



DROP TRIGGER TUB_APPAAL_INSTANCE;



DROP TRIGGER C_TIBUR_KEY_USAGE_CATEGORY;



DROP TRIGGER TUB_X509_KEY_USAGE_CAT;



DROP TRIGGER C_TIUBR_VAL_VOE_STATE;



DROP TRIGGER TUB_VAL_VOE_STATE;



DROP TRIGGER C_TIUBR_APPAAL;



DROP TRIGGER TIB_APPAAL;



DROP TRIGGER TUB_APPAAL;



DROP TRIGGER C_TIUBR_VAL_DEVICE_FUNCTION_TY;



DROP TRIGGER TUB_VAL_DEVICE_FUNCTION_TYPE;



DROP TRIGGER C_TIUBR_KERBEROS_REALM;



DROP TRIGGER TIB_KERBEROS_REALM;



DROP TRIGGER TUB_KERBEROS_REALM;



DROP TRIGGER C_TIUBR_SW_PACKAGE_RELEASE;



DROP TRIGGER TIB_SW_PACKAGE_RELEASE;



DROP TRIGGER TUB_SW_PACKAGE_RELEASE;



DROP TRIGGER C_TIUBR_STATIC_ROUTE;



DROP TRIGGER TIB_STATIC_ROUTE;



DROP TRIGGER TUB_STATIC_ROUTE;



DROP TRIGGER C_TIUBR_VAL_BAUD;



DROP TRIGGER TUB_VAL_BAUD;



DROP TRIGGER C_TIUBR_VAL_NETWORK_SERVICE_TY;



DROP TRIGGER TUB_VAL_NETWORK_SERVICE_TYPE;



DROP TRIGGER C_TIUBR_SYS_USR_AUTH_QUESTION;



DROP TRIGGER TUB_SYSTEM_USER_AUTH_QUESTION;



DROP TRIGGER C_TIUBR_SYSTEM_USER_PHONE;



DROP TRIGGER TIB_SYSTEM_USER_PHONE;



DROP TRIGGER TUB_SYSTEM_USER_PHONE;



DROP TRIGGER C_TIUBR_VAL_IMAGE_TYPE;



DROP TRIGGER TUB_VAL_IMAGE_TYPE;



DROP TRIGGER C_TIUBR_SYSTEM_USER_IMAGE;



DROP TRIGGER TIB_SYSTEM_USER_IMAGE;



DROP TRIGGER TUB_SYSTEM_USER_IMAGE;



DROP TRIGGER C_TIUBR_KEY_USAGE_ATTRB;



DROP TRIGGER TUB_KEY_USAGE_ATTRB;



DROP TRIGGER C_TIUBR_VAL_TOKEN_COL_TYPE;



DROP TRIGGER TUB_TOKEN_COL_TYPE;



DROP TRIGGER C_TIUBR_OPERATING_SYSTEM;



DROP TRIGGER TIB_OPERATING_SYSTEM;



DROP TRIGGER TUB_OPERATING_SYSTEM;



DROP TRIGGER C_TIUBR_VAL_DEVICE_COLLECTION_;



DROP TRIGGER TUB_VAL_DEVICE_COLLECTION_TYPE;



DROP TRIGGER C_TIUBR_SYSTEM_USER_AUTH_LOG;



DROP TRIGGER TIB_SYSTEM_USER_AUTH_LOG;



DROP TRIGGER TUB_SYSTEM_USER_AUTH_LOG;



DROP TRIGGER C_TIUBR_VAL_ENCAPSULATION_TYPE;



DROP TRIGGER TUB_VAL_ENCAPSULATION_TYPE;



DROP TRIGGER C_TIUBR_DEVICE_COLLECTION_HIER;



DROP TRIGGER TUB_DEVICE_COLLECTION_HIER;



DROP TRIGGER C_TIUBR_ENCRYPTION_KEY;



DROP TRIGGER TIB_ENCRYPTION_KEY;



DROP TRIGGER TUB_ENCRYPTION_KEY;



DROP TRIGGER C_TIUBR_VONAGE_OPERATING_ENV;



DROP TRIGGER TIB_VONAGE_OPERATING_ENV;



DROP TRIGGER TUB_VONAGE_OPERATING_ENV;



DROP TRIGGER C_TIUBR_DEVICE_COLLECTION;



DROP TRIGGER TIB_DEVICE_COLLECTION;



DROP TRIGGER TUB_DEVICE_COLLECTION;



DROP TRIGGER C_TIUBR_SW_PACKAGE_REPOSITORY;



DROP TRIGGER TIB_SW_PACKAGE_REPOSITORY;



DROP TRIGGER TUB_SW_PACKAGE_REPOSITORY;



DROP TRIGGER R_TIUBR_VAL_NETWORK_INT_TYPE;



DROP TRIGGER TUB_VAL_NETWORK_INTERFACE_TYPE;



DROP TRIGGER C_TIUBR_DEV_COLL_ASSIGND_CERT;



DROP TRIGGER K_TIUBR_DEV_COLL_ASSIGND_CERT;



DROP TRIGGER TUB_DEV_COLL_ASSIGND_CERT;



DROP TRIGGER C_TIUBR_SYSTEM_PASSWORD;



DROP TRIGGER TUB_SYSTEM_PASSWORD;



DROP TRIGGER C_TIBUR_X509_KEY_USAGE;



DROP TRIGGER TUB_X509_KEY_USAGE;



DROP TRIGGER C_TIUBR_VAL_BADGE_STATUS;



DROP TRIGGER TUB_VAL_BADGE_STATUS;



DROP TRIGGER C_TIUBR_NETBLOCK;



DROP TRIGGER K_TAIU_NONROW_NETBLOCK;



DROP TRIGGER K_TBIU_NETBLOCK;



DROP TRIGGER K_TBIU_NONROW_NETBLOCK;



DROP TRIGGER K_TIUB_NETBLOCK;



DROP TRIGGER TIB_NETBLOCK;



DROP TRIGGER TUB_NETBLOCK;



DROP TRIGGER C_TIUBR_SYS_USER_ASSIGND_CERT;



DROP TRIGGER TUB_SYS_USER_ASSIGND_CERT;



DROP TRIGGER C_TIUBR_DEVICE_NOTE;



DROP TRIGGER TIB_DEVICE_NOTE;



DROP TRIGGER TUB_DEVICE_NOTE;



DROP TRIGGER C_TIUBR_SW_PACKAGE_RELATION;



DROP TRIGGER TIB_SW_PACKAGE_RELATION;



DROP TRIGGER TUB_SW_PACKAGE_RELATION;



DROP TRIGGER C_TIUBR_VAL_UCLASS_TYPE;



DROP TRIGGER TUB_VAL_UCLASS_TYPE;



DROP TRIGGER C_TIUBR_DNS_RECORD;



DROP TRIGGER K_TIUDBR_DNS_RECORD;



DROP TRIGGER TIB_DNS_RECORD;



DROP TRIGGER TUB_DNS_RECORD;



DROP TRIGGER C_TIUBR_SYSTEM_USER_NOTE;



DROP TRIGGER TIB_SYSTEM_USER_NOTE;



DROP TRIGGER TUB_SYSTEM_USER_NOTE;



DROP TRIGGER C_TIUBR_DEVICE_TYPE_PHYS_PORT_;



DROP TRIGGER TUB_DEVICE_TYPE_PHYS_PORT_TEMP;



DROP TRIGGER C_TIUBR_ENCAPSULATION;



DROP TRIGGER TIB_ENCAPSULATION;



DROP TRIGGER TUB_ENCAPSULATION;



DROP TRIGGER C_TIUBR_DNS_RECORD_RELATION;



DROP TRIGGER TUB_DNS_RECORD_RELATION;



DROP TRIGGER C_TIUBR_DEPT;



DROP TRIGGER TIB_DEPT;



DROP TRIGGER TUB_DEPT;



DROP TRIGGER C_TIUBR_VAL_ENCRYPT_METHOD;



DROP TRIGGER C_TUB_VAL_ENCRYPT_METHOD;



DROP TRIGGER C_TIUBR_COMPANY;



DROP TRIGGER TIB_COMPANY;



DROP TRIGGER TUB_COMPANY;



DROP TRIGGER C_TIUBR_VAL_APP_KEY;



DROP TRIGGER TUB_VAL_APP_KEY;



DROP TRIGGER C_TIUBR_DEVICE_POWER_CONNECTIO;



DROP TRIGGER TIB_DEVICE_POWER_CONNECTION;



DROP TRIGGER TUB_DEVICE_POWER_CONNECTION;



DROP TRIGGER C_TIUBR_KLOGIN;



DROP TRIGGER TIB_KLOGIN;



DROP TRIGGER TUB_KLOGIN;



DROP TRIGGER C_TIUBR_SYSTEM_USER_TOKEN;



DROP TRIGGER TUB_SYSTEM_USER_TOKEN;



DROP TRIGGER C_TIUBR_UCLASS;



DROP TRIGGER TIB_UCLASS;



DROP TRIGGER TUB_UCLASS;



DROP TRIGGER C_TIUBR_VAL_PROCESSOR_ARCHITEC;



DROP TRIGGER TUB_VAL_PROCESSOR_ARCHITECTURE;



DROP TRIGGER C_TIUBR_SYSTEM_USER;



DROP TRIGGER K_TAIU_SYSTEM_USER_TYPE;



DROP TRIGGER K_TAIU_SYS_USER_COMPANY;



DROP TRIGGER K_TAU_SYS_USER_STATUS;



DROP TRIGGER K_TIB_SYSTEM_USER;



DROP TRIGGER K_TIUBR_SYSTEM_USER_VATT;



DROP TRIGGER TUB_SYSTEM_USER;



DROP TRIGGER C_TIUBR_SYSTEM_PARKING_PASS;



DROP TRIGGER TIB_SYSTEM_PARKING_PASS;



DROP TRIGGER TUB_SYSTEM_PARKING_PASS;



DROP TRIGGER C_TIUBR_SECONDARY_NETBLOCK;



DROP TRIGGER TIB_SECONDARY_NETBLOCK;



DROP TRIGGER TUB_SECONDARY_NETBLOCK;



DROP TRIGGER C_TIUBR_SITE;



DROP TRIGGER TUB_SITE;



DROP TRIGGER C_TIUBR_COL_MEMBR;



DROP TRIGGER TUB_TOKEN_COL_MEMBR;



DROP TRIGGER C_TIUBR_VAL_CABLE_TYPE;



DROP TRIGGER TUB_VAL_CABLE_TYPE;



DROP TRIGGER C_TIUBR_VAL_AUTH_QUESTION;



DROP TRIGGER TIB_VAL_AUTH_QUESTION;



DROP TRIGGER TUB_VAL_AUTH_QUESTION;



DROP TRIGGER C_TIUBR_VAL_DNS_TYPE;



DROP TRIGGER TUB_VAL_DNS_TYPE;



DROP TRIGGER R_TIUBR_VAL_NETWORK_INT_PURP;



DROP TRIGGER TUB_VAL_NETWORK_INTERFACE_PURP;



DROP TRIGGER C_TIUBR_DEVICE_POWER_INTERFACE;



DROP TRIGGER TUB_DEVICE_POWER_INTERFACE;



DROP TRIGGER C_TIUBR_X509_CERTIFICATE;



DROP TRIGGER TIB_X509_CERTIFICATE;



DROP TRIGGER TUB_X509_CERTIFICATE;



DROP TRIGGER C_TIUBR_TOKEN_COLLECTION;



DROP TRIGGER TIB_TOKEN_COLLECTION;



DROP TRIGGER TUB_TOKEN_COLLECTION;



DROP TRIGGER C_TIUBR_DEVICE_TYPE;



DROP TRIGGER TIB_DEVICE_TYPE;



DROP TRIGGER TUB_DEVICE_TYPE;



DROP TRIGGER C_TIUBR_VOE_RELATION;



DROP TRIGGER TUB_VOE_RELATION;



DROP TRIGGER C_TIUBR_CERT_FILE_FMT;



DROP TRIGGER TUB_CERT_FILE_FMT;



DROP TRIGGER C_TIUBR_APPAAL_INSTANCE_PROPER;



DROP TRIGGER TUB_APPAAL_INSTANCE_PROPERTY;



DROP TRIGGER C_TIUBR_VAL_DNS_SRV_SERVICE;



DROP TRIGGER TUB_VAL_DNS_SRV_SERVICE;



DROP TRIGGER C_TIUBR_VAL_AUTH_RESOURCE;



DROP TRIGGER TUB_VAL_AUTH_RESOURCE;



DROP TRIGGER C_TIUBR_VAL_PRODUCTION_STATE;



DROP TRIGGER TUB_VAL_PRODUCTION_STATE;



DROP TRIGGER C_TIUBR_VAL_PASSWORD_TYPE;



DROP TRIGGER TUB_VAL_PASSWORD_TYPE;



DROP TRIGGER C_TIUBR_VAL_COUNTRY_CODE;



DROP TRIGGER TUB_VAL_COUNTRY_CODE;



COMMENT ON COLUMN APPAAL_INSTANCE_PROPERTY.ENCRYPTION_KEY_ID IS 'encryption information for app_value, if used';



COMMENT ON TABLE DEVICE_COLLECTION_ASSIGND_CERT IS 'Actual assignment of the usage category APPLICATION Certificates to Device Collections.';



COMMENT ON COLUMN DEVICE_COLLECTION_ASSIGND_CERT.X509_CERT_ID IS 'Uniquely identifies Certificate';



COMMENT ON COLUMN DEVICE_COLLECTION_ASSIGND_CERT.X509_KEY_USG IS 'Name of the Certificate.';



COMMENT ON COLUMN DEVICE_COLLECTION_ASSIGND_CERT.X509_FILE_FORMAT IS 'Format Name of the file containing Certificate information. Example; keytool, rsa';



COMMENT ON COLUMN DEVICE_COLLECTION_ASSIGND_CERT.FILE_LOCATION_PATH IS 'Alphanumeric representation of the path leading to the file.';



COMMENT ON COLUMN DEVICE_COLLECTION_ASSIGND_CERT.KEY_TOOL_LABEL IS 'Alphanumeric representation of the label attached to the certificate by Key Tool';



COMMENT ON COLUMN DEVICE_COLLECTION_ASSIGND_CERT.FILE_ACCESS_MODE IS 'Numeric representation of the File Access Mode.';



COMMENT ON COLUMN DEVICE_COLLECTION_ASSIGND_CERT.FILE_OWNER_SYSTEM_USER_ID IS 'Identifier of the file owner.';



COMMENT ON COLUMN DEVICE_COLLECTION_ASSIGND_CERT.FILE_GROUP_UCLASS_ID IS 'Identifies uclass that corresponds to a unix group';



COMMENT ON COLUMN DEVICE_COLLECTION_ASSIGND_CERT.KEY_USAGE_REASON_FOR_ASSIGN IS 'Uniquely identifies and indicates reason for assignment.';



COMMENT ON TABLE DEVICE_TICKET IS 'associates devices and trouble tickets together (external to sysdb)';



COMMENT ON COLUMN DEVICE_TICKET.TICKET_NUMBER IS 'trouble ticketing system id';



COMMENT ON COLUMN DEVICE_TICKET.IS_PHYSICAL IS 'indicates that the ticket pertains to the physical device as opposed to a function associated with the device';



COMMENT ON COLUMN DEVICE_TICKET.NOTES IS 'free form notes about the ticket/device association';



COMMENT ON TABLE ENCRYPTION_KEY IS 'Keep information on keys used to encrypt sensitive data in the schema';



COMMENT ON COLUMN ENCRYPTION_KEY.ENCRYPTION_KEY_DB_VALUE IS 'part of 3-tuple that is the key used to encrypt. The other portions are provided by a user and stored in the key_crypto package';



COMMENT ON COLUMN ENCRYPTION_KEY.ENCRYPTION_KEY_PURPOSE IS 'indicates the purpose of infrastructure providing the key. Used externally by applications to manage their portion of the key';



COMMENT ON COLUMN ENCRYPTION_KEY.ENCRYPTION_KEY_PURPOSE_VERSION IS 'indicates the version of the application portion of the key. Used externally by applications to manage their portion of the key';



COMMENT ON COLUMN ENCRYPTION_KEY.ENCRYPTION_METHOD IS 'Text representation of the method of encryption. Format is the same as Kerberos uses such as in rfc3962';



COMMENT ON TABLE PROPERTY IS 'generic property instance that describes system wide properties, as well as properties for various values of columns used throughout the db for configuration, acls, defaults, etc; also used to relate some tables';



COMMENT ON COLUMN PROPERTY.PROPERTY_ID IS 'primary key for table to uniquely identify rows. Values came from uclass_property_override or were contrived in 2009Q2 with the property migration.';



COMMENT ON COLUMN PROPERTY.COMPANY_ID IS 'company that properties may be set on.';



COMMENT ON COLUMN PROPERTY.DEVICE_COLLECTION_ID IS 'device collection that properties may be set on.';



COMMENT ON COLUMN PROPERTY.DNS_DOMAIN_ID IS 'dns domain that properties may be set on.';



COMMENT ON COLUMN PROPERTY.OPERATING_SYSTEM_ID IS 'operating system that properties may be set on.';



COMMENT ON COLUMN PROPERTY.SITE_CODE IS 'site_code that properties may be set on';



COMMENT ON COLUMN PROPERTY.SYSTEM_USER_ID IS 'system user that properties may be set on.';



COMMENT ON COLUMN PROPERTY.UCLASS_ID IS 'uclass that properties may be set on.';



COMMENT ON COLUMN PROPERTY.PROPERTY_NAME IS 'textual name of a property';



COMMENT ON COLUMN PROPERTY.PROPERTY_TYPE IS 'textual type of a department';



COMMENT ON COLUMN PROPERTY.PROPERTY_VALUE IS 'general purpose column for value of property not defined by other types. This may be enforced by fk (trigger) if val_property.property_data_type is list (fk is to val_property_value).';



COMMENT ON COLUMN PROPERTY.PROPERTY_VALUE_TIMESTAMP IS 'property is defined as a timestamp';



COMMENT ON COLUMN PROPERTY.START_DATE IS 'date/time that the assignment takes effect';



COMMENT ON COLUMN PROPERTY.FINISH_DATE IS 'date/time that the assignment ceases taking effect';



COMMENT ON COLUMN PROPERTY.IS_ENABLED IS 'indiciates if the property is temporarily disabled or not.';



COMMENT ON TABLE SYSTEM_USER_ASSIGND_CERT IS 'Actual assignment of the usage category USER Certificates to System Users.';



COMMENT ON COLUMN SYSTEM_USER_ASSIGND_CERT.X509_CERT_ID IS 'Uniquely identifies Certificate';



COMMENT ON COLUMN SYSTEM_USER_ASSIGND_CERT.X509_KEY_USG IS 'Name of the Certificate.';



COMMENT ON COLUMN SYSTEM_USER_ASSIGND_CERT.KEY_USAGE_REASON_FOR_ASSIGN IS 'Uniquely identifies and indicates reason for assignment.';



COMMENT ON TABLE SYSTEM_USER_AUTH_LOG IS 'Captures all system user authorizations for access to Vonage resources.';



COMMENT ON COLUMN SYSTEM_USER_AUTH_LOG.SYSTEM_USER_AUTH_SEQ IS 'This sequence is to support table PK with timestamps recived rounded to the secend and generating duplicates.';



COMMENT ON COLUMN SYSTEM_USER_AUTH_LOG.AUTH_RESOURCE_INSTANCE IS 'Keeps track of the server where a user was authenticating for a given resource';



COMMENT ON COLUMN SYSTEM_USER_AUTH_LOG.AUTH_ORIGIN IS 'Keeps track of where the request for authentication originated from.';



COMMENT ON TABLE SYSTEM_USER_AUTH_QUESTION IS 'Captures system user chosen answers to the set of predetermined questions for user authentication purposes.';



COMMENT ON COLUMN SYSTEM_USER_AUTH_QUESTION.SYSTEM_USER_ID IS 'Uniquely identifies system user.';



COMMENT ON COLUMN SYSTEM_USER_AUTH_QUESTION.AUTH_QUESTION_ID IS 'Uniquely identifies authentication question.';



COMMENT ON COLUMN SYSTEM_USER_AUTH_QUESTION.USER_ANSWER IS 'Records system user answer to the authentication question.';



COMMENT ON COLUMN TOKEN.ENCRYPTION_KEY_ID IS 'encryption information for token_key, if used';



COMMENT ON TABLE TOKEN_COLLECTION IS 'Group tokens together in arbitrary ways.';



COMMENT ON TABLE TOKEN_COLLECTION_MEMBER IS 'Assign individual tokens to groups.';



COMMENT ON TABLE VAL_ENCRYPTION_KEY_PURPOSE IS 'Valid purpose of encryption used by the key_crypto package; Used to identify which functional application knows the app provided portion of the encryption key';



COMMENT ON TABLE VAL_ENCRYPTION_METHOD IS 'List of text representations of methods of encryption. Format is the same as Kerberos uses such as in rfc3962';



COMMENT ON TABLE VAL_KEY_USG_REASON_FOR_ASSGN IS 'Identifies a reason why certificate has been assigned a given key usage attribute.';



COMMENT ON COLUMN VAL_KEY_USG_REASON_FOR_ASSGN.KEY_USAGE_REASON_FOR_ASSIGN IS 'Uniquely identifies and indicates reason for assignment.';



COMMENT ON TABLE VAL_PROPERTY IS 'valid values and attributes for (name,type) pairs in the property table';



COMMENT ON COLUMN VAL_PROPERTY.PROPERTY_NAME IS 'property name for validation purposes';



COMMENT ON COLUMN VAL_PROPERTY.PROPERTY_TYPE IS 'property type for validation purposes';



COMMENT ON COLUMN VAL_PROPERTY.IS_MULTIVALUE IS 'If N, acts like an ak on property.(*_id,property_type)';



COMMENT ON COLUMN VAL_PROPERTY.PROPERTY_DATA_TYPE IS 'which of the property_table_* columns should be used for this value';



COMMENT ON COLUMN VAL_PROPERTY.PERMIT_COMPANY_ID IS 'defines how company id should be used in the property for this (name,type)';



COMMENT ON COLUMN VAL_PROPERTY.PERMIT_DEVICE_COLLECTION_ID IS 'defines how company id should be used in the property for this (name,type)';



COMMENT ON COLUMN VAL_PROPERTY.PERMIT_DNS_DOMAIN_ID IS 'defines how company id should be used in the property for this (name,type)';



COMMENT ON COLUMN VAL_PROPERTY.PERMIT_SYSTEM_USER_ID IS 'defines how company id should be used in the property for this (name,type)';



COMMENT ON COLUMN VAL_PROPERTY.PERMIT_UCLASS_ID IS 'defines how company id should be used in the property for this (name,type)';



COMMENT ON TABLE VAL_PROPERTY_DATA_TYPE IS 'valid data types for property (name,type) pairs';



COMMENT ON TABLE VAL_PROPERTY_TYPE IS 'validation table for property types';



COMMENT ON COLUMN VAL_PROPERTY_VALUE.PROPERTY_NAME IS 'property name for validation purposes';



COMMENT ON COLUMN VAL_PROPERTY_VALUE.PROPERTY_TYPE IS 'property type for validation purposes';



COMMENT ON COLUMN VAL_PROPERTY_VALUE.VALID_PROPERTY_VALUE IS 'if applicatable, servves as a fk for valid property_values. This depends on val_property.property_data_type being set to list.';



COMMENT ON TABLE VAL_TOKEN_COLLECTION_TYPE IS 'Assign purposes to arbitrary groupings';



COMMENT ON TABLE VAL_X509_CERTIFICATE_FILE_FMT IS 'Format of the file containing certificate.';



COMMENT ON COLUMN VAL_X509_CERTIFICATE_FILE_FMT.X509_FILE_FORMAT IS 'Format Name of the file containing Certificate information. Example; keytool, rsa';



COMMENT ON TABLE VAL_X509_KEY_USAGE IS 'Captures possible usage of the certificate key. Example: Client, Server, CA.';



COMMENT ON COLUMN VAL_X509_KEY_USAGE.X509_KEY_USG IS 'Name of the Certificate.';



COMMENT ON COLUMN VAL_X509_KEY_USAGE.DESCRIPTION IS 'Textual Description of the certificate key usage.';



COMMENT ON COLUMN VAL_X509_KEY_USAGE.IS_EXTENDED IS 'Indicates if certificate key is to have an extended key usage. Default is ''N'' - No.';



COMMENT ON TABLE VAL_X509_KEY_USAGE_CATEGORY IS 'Categorizes Certificates based on the technology object the usage can be assigned to. Currently: Application, User.';



COMMENT ON COLUMN VAL_X509_KEY_USAGE_CATEGORY.X509_KEY_USG_CAT IS 'Category Name. Example: Application.';



COMMENT ON COLUMN VAL_X509_KEY_USAGE_CATEGORY.DESCRIPTION IS 'Textual description of the category.';



COMMENT ON TABLE X509_CERTIFICATE IS 'X509 specification Certificate.';



COMMENT ON COLUMN X509_CERTIFICATE.X509_CERT_ID IS 'Uniquely identifies Certificate';



COMMENT ON COLUMN X509_CERTIFICATE.SIGNING_CERT_ID IS 'Identifier for the certificate that has signed this one.';



COMMENT ON COLUMN X509_CERTIFICATE.X509_CA_CERT_SERIAL_NUMBER IS 'Serial number assigned to the certificate within Certificate Authority. It uniquely identifies certificate within the realm of the CA.';



COMMENT ON COLUMN X509_CERTIFICATE.PUBLIC_KEY IS 'Textual representation of Certificate Public Key. Public Key is a component of X509 standard and is used for encryption.';



COMMENT ON COLUMN X509_CERTIFICATE.PRIVATE_KEY IS 'Textual representation of Certificate Private Key. Private Key is a component of X509 standard and is used for encryption.';



COMMENT ON COLUMN X509_CERTIFICATE.CERT_SIGNING_RQST IS 'Textual representation of a CSR. In public key infrastructure systems, a certificate signing request (also CSR or certification request) is a message sent from an applicant to a certificate authority in order to apply for a digital identity certificate.';



COMMENT ON COLUMN X509_CERTIFICATE.SUBJECT IS 'Textual representation of a certificate subject. Certificate subject is a part of X509 certificate specifications.';



COMMENT ON COLUMN X509_CERTIFICATE.VALID_FROM IS 'Timestamp indicating when the certificate becomes valid and can be used.';



COMMENT ON COLUMN X509_CERTIFICATE.VALID_TO IS 'Timestamp indicating when the certificate becomes invalid and can''t be used.';



COMMENT ON COLUMN X509_CERTIFICATE.IS_CERT_REVOKED IS 'Indicates if certificate has been revoked. ''Y'' indicates that Certificate has been revoked.';



COMMENT ON TABLE X509_KEY_USAGE_ATTRIBUTE IS 'Actual attribute of certificate key usage.';



COMMENT ON COLUMN X509_KEY_USAGE_ATTRIBUTE.X509_CERT_ID IS 'Uniquely identifies Certificate';



COMMENT ON COLUMN X509_KEY_USAGE_ATTRIBUTE.X509_KEY_USG IS 'Name of the Certificate.';



COMMENT ON COLUMN X509_KEY_USAGE_ATTRIBUTE.X509_KEY_USG_CAT IS 'Category Name. Example: Application.';



COMMENT ON TABLE X509_KEY_USAGE_CATEGORIZATION IS 'Captures certificate key usage categorization. Example: Client key usage can be assigned to USER, but CA usage can not.';



COMMENT ON COLUMN X509_KEY_USAGE_CATEGORIZATION.X509_KEY_USG_CAT IS 'Category Name. Example: Application.';



COMMENT ON COLUMN X509_KEY_USAGE_CATEGORIZATION.X509_KEY_USG IS 'Name of the Certificate.';


