#!/bin/sh
# Copyright (c) 2005-2010, Vonage Holdings Corp.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY VONAGE HOLDINGS CORP. ''AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL VONAGE HOLDINGS CORP. BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Copyright (c) 2013-1016, Todd M. Kover
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


#
# $Id$
#

PATH=usr/local/bin:/usr/local/sbin:/usr/vendor/bin:/usr/kerberos/bin:/usr/bin:/bin
export PATH

ZG_ROOT=/var/lib/zonegen
LOCKFILE=${ZG_ROOT}/run/zonegen.lock

if [ ! -r ${ZG_ROOT} ] ; then
	mkdir -p ${ZG_ROOT}
	mkdir -p ${ZG_ROOT}/run
	mkdir -p ${ZG_ROOT}/auto-gen
	mkdir -p ${ZG_ROOT}/auto-gen/perserver
fi

# redirect debugging to /dev/null unless this is a tty
exec 3>/dev/null
tty -s
if [ $? = 0 ] ; then
	exec 3>&2
fi

cleanup() {
	echo 1>&2 cleaning up lockfile after signal
	rm -f $LOCKFILE
	exit 1
}

dorsync() {
	host=$1
	zoneroot=$2

	rsync </dev/null -l -rpt --delete-after $zoneroot/zones $zoneroot/etc ${host}:$DST_ROOT
	cat $zoneroot/etc/zones-changed | $RSYNC_RSH >/dev/null $host /usr/libexec/jazzhands/zonegen/ingest-zonegen-changes
}

trap cleanup HUP INT TERM

tty >/dev/null 2>&1
#
# if we're not a tty, do away with output
#
if [ $? = 1 ] ; then
	exec >/dev/null
	exec 2>/dev/null
fi

list=`find 2>/dev/null $LOCKFILE -mmin +180`
if [ ! -z "$list" ] ; then
	echo 1>&3 removing lockfile $LOCKFILE as three hours has past.
	rm -f $LOCKFILE
fi

umask 022

lockingon=no
if [ -z "$*" ] ; then
	if [ -r $LOCKFILE ] ; then
		echo 1>&2 Locked, Skipping.
		exit 0
	fi
	echo Locking
	lockingon=yes
	touch $LOCKFILE
fi

PERSERVER_HOSTFILE=/etc/jazzhands/zonegen-perserver.conf

LISTGEN=/usr/libxec/jazzhands/zonegen/generate-list

SRC_ROOT=${ZG_ROOT}/auto-gen
DST_ROOT=/var/named/chroot/auto-gen
RSYNC_RSH=/usr/libexec/jazzhands/zonegen/ssh-wrap

export RSYNC_RSH

if [ ! -x ${RSYNC_RSH} ] ; then
	RSYNC_RSH=ssh
fi

KRB5CCNAME=/tmp/krb5cc_zonegen_$$_do_zonegen
export KRB5CCNAME

if [ -x  /usr/libexec/jazzhands/zonegen/generate-zones ] ; then
	echo 1>&3  "Generating Zones (This may take a while)..."
	/usr/libexec/jazzhands/zonegen/generate-zones "$@" >&3
	ec=$?
	if [ $ec != 0 ] ; then
		rm -f $LOCKFILE
		exit $ec
	fi

	#
	# if the list of hosts to rsync to was generated by zonegen, use it
	#
	if [ -f ${ZG_ROOT}/auto-gen/rsynchostlist.txt ] ; then
		DSTFILES=${ZG_ROOT}/auto-gen/rsynchostlist.txt
	elif [ -r "$PERSERVER_HOSTFILE" ] ; then
		DSTFILES=$PERSERVER_HOSTFILE
	fi

	#
	# prune temporary files not from today, since presumably they have been
	# cleaned up already.
	#
	find $ZG_ROOT/auto-gen/zones -name '*.tmp.[0-9]*' -mmin +1440 -print0 |xargs -0 rm -f

	if [ -f /etc/krb5.keytab.zonegen ] ; then
		kinit -k -t /etc/krb5.keytab.zonegen zonegen
	fi
	for hostfile in $DSTFILES ; do
		if [ -r "$hostfile" ] ; then
			echo 1>&3 Processing file $hostfile
			sed -e 's/#.*//' $hostfile |
			while read ns servers ; do
				if [ "$servers" = "" ] ; then
					servers="$ns"
					ns=""
				fi
				servers=`echo $servers | sed 's/,/ /'`
				for host in $servers ; do
					if [ x"$host" != "x" ] ;then
						if [ "$ns" = "" ] ; then
							echo 1>&3  "Rsyncing to $host ..."
							dorsync $host "$SRC_ROOT"
						else
							echo 1>&3  "Rsyncing to $host (in $ns) ..."
							dorsync $host "$SRC_ROOT/perserver/$ns"
						fi
					fi
				done
			done
		fi
	done
fi

if [ "$lockingon" = "yes" ] ; then
	echo 1>&3 Unlocking
	rm -f $LOCKFILE
fi

kdestroy >/dev/null 2>&1

exit 0
